name: "Sphinx: Render and Deploy docs"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package + docs deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
          python -m pip install "napari[pyqt5]"
      
      - name: Build HTML
        working-directory: documentation
        env:
          QT_QPA_PLATFORM: offscreen
          MPLBACKEND: Agg
        run: |
          mkdir -p _static
          make clean
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentation/build/html
          keep_files: false
