# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: tests

on:
  push:
    tags: ["*"]
    branches:
      - main
      - npe2
  release:
    types: [released]
  pull_request:
    branches:
      - main
      - npe2
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: "true"

      - name: Install Windows OpenGL
        uses: pyvista/setup-headless-display-action@v4.2
        with:
          qt: true
          wm: herbstluftwm

      - name: Clean up before build
        run: |
          find . -type d -name "__pycache__" -exec rm -r {} + || true
          find . -type f -name "*.pyc" -delete || true

      - name: Test with tox
        run: uvx --with tox-gh-actions tox
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Coverage
        uses: codecov/codecov-action@v5

  build-and-inspect-package:
    name: Build & inspect package.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Clean up before build
        run: |
          find . -type d -name "__pycache__" -exec rm -r {} + || true
          find . -type f -name "*.pyc" -delete || true

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools-scm build

      - uses: hynek/build-and-inspect-python-package@v2

  deploy:
    needs: [test, build-and-inspect-package]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download built artifact to dist/
        uses: actions/download-artifact@v5
        with:
          name: Packages
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
